# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            سالار مقدم
tagline:          'SalarMgh'
description:      '*nix Sysadmin & DevOps'
url:              http://salarmgh.github.io
baseurl:          /

author:
  name:           'Salar Moghaddam'
  url:            https://twitter.com/salarmgh

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/salarmgh
gems: [jekyll-paginate, jekyll-gist]
dir: rtl
excerpt_separator: "<!--excerpt-->"